language: java
jdk:
- oraclejdk8
install:
- gradle test
- exit 0
notifications:
  email:
    on_success: never
    on_failure: always
env:
  global:
  - secure: khGRZe4xoNWCaz+7Ocb4tjPQPnxTaQAB2nSqK15FeglvMDrpJsJXs0tbC3YUCwk/85/odehaWP/yTp4glhkE9/8Q67iil+QaVzYrfWrd8WHBsPJY7VcZkH8InGDNObovkflo4SSLspDt5UObywGA+Gq8pNr9chbU4fIEzuaAwewXCZTYa+sFTRObhkyMcgWwwO+h2aAAKqFRiR/CmwOB2nekV47F0PPpvlTgxcVYAtDkS+kDzM9lGgKssqm+k7RtNxSBP6bYe9yJZ5kbW3MNlm2lCF2YwRPI35XghQ99hh1f8chycq0g+UaIC6ZT5+HQwL3INJDqpGAMZki+xCk/QCGIHw/ZRzvuWpFzXqFg0Yk7z4w0A6xtOEm7t9mcMSZkwYpZsiBdFsM+amWafrcl5CTX7brOnzbzLTdwKz5LrKrzhK1x3C9SqbZgDbxqWglaEGPdoGhlr95/B2ZoOYD+7o14uE8IQM0f80WfG5nyXhhx5tmisBTa/8DlgZVgdo5RdwO6IFfSyrZ625ZA/n6+I7c+J0jIpQQOpJ2d4jjdETmkRQgLGC239AwrULqXktsv0+QFeh1vRYM18Bnyvbr70k8XYiMM8ueB22dtdxzZ86jW26YUBA43pyxexk37gganK++yEFmUOYvo3Cgx2tQotbpwVedeTtEdB74BvJlG0W8=
  - secure: ehnevsH0817sSfHS65zUvo13bDh6aIhDyyDhwMMZQc+BcBz3K1wEjagnPpZ6SWGD8XIowLcfbAAytw5BfHPNeH3LBxwrRdU819jomKqCgXYhSgwvnJ+ZusDPmA0ZRJTwHej4xdyBMs/8pobyb7cvhj0y1qk5ja0R7TKIAWYRF7DV3LfVkDmU1XbZOQkkQ2DZNbfTiCT2gjTUbLJ61dZmnWjkgADa+T1Fe6R7VX3jqDu8qeCGmY/s7o8Fp1rWLPmdd8ShAiHJr0h1EJGPyDd67H03F54ill3Lc8sUWuCRq5yAdvT/Z1/puQKt8Djg2lPimVVOjVuVkpshvdn51RWSYFk0iga/5ABur6hZTyAIB9zh3O4x3h2Heo6b8ApiGaJtiWjIFmDjB5VWsDVaAB2SGx9lImVnHVJ9W7ARQjWAVo1Dcy3TUI953HEZ9aqgkcwwHWKIOEPLMM0ukPqjws4asUMGLQ45mFIL64VXTksWXAcL646P0BCEFaClV/wbeNhtKm1awTMk7IYja5fsJ+WIyx3YJa8tL2eF5EGhSxbkM/829FErqioejIvajgL57nhN9pKx5X449CLoDiF53rhkzBLTkTUfyDgUvYDl9ASOSOhbZCrKMv2axXcY33NVau00YKj9uPRrzmu54zqvzJOjgOoaEXXox42TumJFBFwWX54=
